const LEGACY_AGENT_RUNTIME_ENV_ALIASES = Object.freeze({
  AGENT_MANIFEST_PATH: "PHASE222_ADAPTER_MANIFEST",
  AGENT_RUNTIME_MODE: "TCAR_ENGINE_MODE",
  AGENT_RUNTIME_API_URL: "TCAR_RUNTIME_API_URL",
  AGENT_RUNTIME_API_KEY: "TCAR_RUNTIME_API_KEY",
  AGENT_RUNTIME_API_KEY_FILE: "TCAR_RUNTIME_API_KEY_FILE",
  AGENT_RUNTIME_HEALTH_TIMEOUT_MS: "TCAR_RUNTIME_HEALTH_TIMEOUT_MS",
  AGENT_RUNTIME_AGENT_LIST_TIMEOUT_MS: "TCAR_RUNTIME_AGENT_LIST_TIMEOUT_MS",
  AGENT_RUNTIME_CHAT_TIMEOUT_MS: "TCAR_RUNTIME_CHAT_TIMEOUT_MS",
  AGENT_RUNTIME_TERMINAL_RECOVERY_MS: "TCAR_RUNTIME_TERMINAL_RECOVERY_MS",
  AGENT_RUNTIME_WORKFLOW_TIMEOUT_MS: "TCAR_RUNTIME_WORKFLOW_TIMEOUT_MS",
  AGENT_RUNTIME_CONTINUATION_TIMEOUT_MS: "TCAR_RUNTIME_CONTINUATION_TIMEOUT_MS",
  AGENT_RUNTIME_ADMIN_TIMEOUT_MS: "TCAR_RUNTIME_ADMIN_TIMEOUT_MS",
  AGENT_RUNTIME_VALIDATION_TIMEOUT_SEC: "TCAR_RUNTIME_VALIDATION_TIMEOUT_SEC",
  AGENT_RUNTIME_CONNECT_TIMEOUT_MS: "TCAR_RUNTIME_CONNECT_TIMEOUT_MS",
  AGENT_RUNTIME_HEADER_TIMEOUT_MS: "TCAR_RUNTIME_HEADER_TIMEOUT_MS",
  AGENT_RUNTIME_BODY_IDLE_TIMEOUT_MS: "TCAR_RUNTIME_BODY_IDLE_TIMEOUT_MS",
  AGENT_RUNTIME_MAX_RESPONSE_BYTES: "TCAR_RUNTIME_MAX_RESPONSE_BYTES",
  AGENT_RUNTIME_ALLOW_LOCAL_RUNTIME_URL: "TCAR_ALLOW_LOCAL_RUNTIME_URL",
  AGENT_RUNTIME_ALLOW_LOOPBACK_RUNTIME_TUNNEL: "TCAR_ALLOW_LOOPBACK_RUNTIME_TUNNEL",
  AGENT_RUNTIME_ALLOW_SAME_ORIGIN_RUNTIME_URL: "TCAR_ALLOW_SAME_ORIGIN_RUNTIME_URL",
  AGENT_RUNTIME_ALLOW_INSECURE_PRIVATE_RUNTIME_HTTP: "TCAR_ALLOW_INSECURE_PRIVATE_RUNTIME_HTTP",
  AGENT_RUNTIME_PLANNER_MAX_TOKENS: "TCAR_PLANNER_MAX_TOKENS",
  AGENT_RUNTIME_MAX_ROUTING_AGENTS: "TCAR_MAX_ROUTING_ADAPTERS",
  AGENT_RUNTIME_MAX_RESOURCE_SUPPORT_AGENTS: "TCAR_MAX_RESOURCE_SUPPORT_ADAPTERS",
  AGENT_RUNTIME_PARALLEL_WORKERS: "TCAR_PARALLEL_WORKERS",
  AGENT_RUNTIME_MAX_TOKENS: "TCAR_MAX_TOKENS",
  AGENT_RUNTIME_REFINER_MAX_TOKENS: "TCAR_REFINER_MAX_TOKENS",
  AGENT_RUNTIME_TEMPERATURE: "TCAR_TEMPERATURE",
  AGENT_RUNTIME_CLIENT_MAX_PLANNER_TOKENS: "TCAR_CLIENT_MAX_PLANNER_TOKENS",
  AGENT_RUNTIME_CLIENT_MAX_ROUTING_AGENTS: "TCAR_CLIENT_MAX_ROUTING_ADAPTERS",
  AGENT_RUNTIME_CLIENT_MAX_PARALLEL_WORKERS: "TCAR_CLIENT_MAX_PARALLEL_WORKERS",
  AGENT_RUNTIME_CLIENT_MAX_TOKENS: "TCAR_CLIENT_MAX_TOKENS",
  AGENT_RUNTIME_CLIENT_MAX_REFINER_TOKENS: "TCAR_CLIENT_MAX_REFINER_TOKENS",
  AGENT_RUNTIME_CLIENT_MAX_TEMPERATURE: "TCAR_CLIENT_MAX_TEMPERATURE",
  AGENT_RUNTIME_MODEL_CONTEXT_TOKENS: "TCAR_MODEL_CONTEXT_TOKENS",
  AGENT_RUNTIME_ORCHESTRATION_MODEL_CONTEXT_TOKENS: "ROUTER_SESSION_CONTEXT_TOKENS",
  AGENT_RUNTIME_ROUTE_INPUT_MAX_TOKENS: "TCAR_ROUTE_INPUT_MAX_TOKENS",
  AGENT_RUNTIME_REFINER_INPUT_MAX_TOKENS: "TCAR_REFINER_INPUT_MAX_TOKENS",
  AGENT_RUNTIME_ROUTE_MIN_INPUT_TOKENS: "TCAR_ROUTE_MIN_INPUT_TOKENS",
  AGENT_RUNTIME_REFINER_MIN_INPUT_TOKENS: "TCAR_REFINER_MIN_INPUT_TOKENS",
  AGENT_RUNTIME_ROUTE_TOKEN_SAFETY_MARGIN: "TCAR_ROUTE_TOKEN_SAFETY_MARGIN",
  AGENT_RUNTIME_COMPLETION_TOKEN_SAFETY_MARGIN: "TCAR_COMPLETION_TOKEN_SAFETY_MARGIN",
  AGENT_RUNTIME_TOOL_MAX_ROUNDS: "TCAR_TOOL_MAX_ROUNDS",
  AGENT_RUNTIME_SHARED_MEMORY_MAX_ENTRIES: "TCAR_SHARED_MEMORY_MAX_ENTRIES",
  AGENT_RUNTIME_SHARED_MEMORY_MAX_ENTRY_CHARS: "TCAR_SHARED_MEMORY_MAX_ENTRY_CHARS",
  AGENT_RUNTIME_SHARED_MEMORY_MAX_TOTAL_CHARS: "TCAR_SHARED_MEMORY_MAX_TOTAL_CHARS",
  AGENT_RUNTIME_SSH_BINARY: "GPU_SSH_BINARY",
  AGENT_RUNTIME_SSH_HOST: "GPU_SSH_HOST",
  AGENT_RUNTIME_SSH_PORT: "GPU_SSH_PORT",
  AGENT_RUNTIME_SSH_USER: "GPU_SSH_USER",
  AGENT_RUNTIME_SSH_IDENTITY_FILE: "GPU_SSH_IDENTITY_FILE",
  AGENT_RUNTIME_SSH_KNOWN_HOSTS_FILE: "GPU_SSH_KNOWN_HOSTS_FILE",
  AGENT_RUNTIME_TUNNEL_LOCAL_HOST: "TCAR_TUNNEL_LOCAL_HOST",
  AGENT_RUNTIME_TUNNEL_LOCAL_PORT: "TCAR_TUNNEL_LOCAL_PORT",
  AGENT_RUNTIME_TUNNEL_RUNTIME_HOST: "TCAR_TUNNEL_RUNTIME_HOST",
  AGENT_RUNTIME_TUNNEL_RUNTIME_PORT: "TCAR_TUNNEL_RUNTIME_PORT"
});

const warnedLegacyNames = new Set();

export function readAgentRuntimeEnv(env, canonicalName, fallback = undefined) {
  const legacyName = LEGACY_AGENT_RUNTIME_ENV_ALIASES[canonicalName];
  if (!legacyName) {
    throw new Error(`Unknown Agent Runtime environment key: ${canonicalName}`);
  }
  const source = env || {};
  if (source[canonicalName] !== undefined) {
    return source[canonicalName];
  }
  if (source[legacyName] !== undefined) {
    warnLegacyAlias(legacyName, canonicalName);
    return source[legacyName];
  }
  return fallback;
}

export function legacyAgentRuntimeEnvAliases() {
  return { ...LEGACY_AGENT_RUNTIME_ENV_ALIASES };
}

export function resetAgentRuntimeEnvAliasWarningsForTests() {
  if (process.env.NODE_ENV !== "test") {
    throw new Error("Agent Runtime environment warning reset is available only in tests.");
  }
  warnedLegacyNames.clear();
}

function warnLegacyAlias(legacyName, canonicalName) {
  if (warnedLegacyNames.has(legacyName)) return;
  warnedLegacyNames.add(legacyName);
  // Environment names are configuration metadata, not values. Never include
  // the resolved value here because the aliased setting may be a secret.
  console.warn("agent_runtime.env_alias_deprecated", {
    legacy_name: legacyName,
    canonical_name: canonicalName
  });
}
