export const BASE_MODEL = "qwen36-awq";
export const DEFAULT_VLLM_BASE_URL = "http://127.0.0.1:8000/v1";

export const seedAgents = [
  {
    id: "finance_reasoning_lora",
    title: "General finance, macroeconomic, market, and quantitative analysis",
    capability: "Provides broad financial and macroeconomic analysis, including country and market comparisons, GDP and growth outlooks, financial statements, valuation, cash flow, fiscal and monetary conditions, scenarios, and quantitative calculations. Uses general model knowledge when current data is unavailable and labels assumptions and uncertainty.",
    boundary: "Give a substantive best-effort answer first. Treat missing or unverified data and regulated-advice limitations as short disclosure notes, not automatic refusal reasons. Distinguish general analysis from personalized professional advice.",
    consumes: ["user_request", "financial_context", "evidence_summary"],
    produces: ["financial_analysis", "calculation_trace", "assumptions", "risk_factors"],
    routing_cues: ["finance", "financial", "financial analysis", "financial situation", "financial statement", "cash flow", "valuation", "loan", "mortgage", "npv", "irr", "portfolio", "stock quote", "annual report", "gdp", "gross domestic product", "economy", "economic outlook", "macroeconomics", "country outlook", "sovereign", "central bank", "inflation", "interest rate", "public debt", "fiscal policy", "monetary policy", "trade balance", "exchange rate", "recession", "economic growth", "global economy"],
    resources: ["general_model_knowledge", "canonical_tool_contracts", "poc_validated_evaluation"],
    tools: ["finance_calculator", "calculator", "web_search", "market_data"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 20,
    skill_path: "skills/tcar_real_loras/finance_reasoning_lora/SKILL.md",
    skill_digest: "2d996fe2fa5df9ec8f08b794bcd9d3c5ac5c366d1f72fa8598c9c0ab5f2363c2",
    adapter_path: "adapters/tcar_real_loras/finance_reasoning_lora",
    contract_version: "tcar-agent-v1",
    policies: {
      activation_policy: "Activate for any request whose main task is financial, economic, macroeconomic, market, banking, valuation, or quantitative finance analysis.",
      write_policy: "Always provide a substantive best-effort answer and begin directly with the analysis. Use general model knowledge and clearly stated assumptions when data is absent; do not open with refusal language, discuss irrelevant route artifacts, expose internal policy labels, or abstain solely because the user supplied no dataset. When a specific number of countries or items is requested, start with a compact list or table containing exactly that many distinct named entries; add broader synthesis only afterward.",
      source_policy: "Prefer approved current sources for exact or time-sensitive figures. If none are available, continue from general model knowledge, label estimates and inference, and append a Data note instead of refusing.",
      tool_policy: "Use tools when they materially help. Do not invent numerical tool inputs or force broad qualitative questions into an unrelated calculator program.",
      citation_policy: "Cite only sources actually supplied by the executor. Never invent citations; lack of citations requires a Data note, not an empty answer.",
      escalation_policy: "For personalized regulated advice, provide useful general analysis first and append a concise professional-advice note. Refuse only when a platform safety rule independently requires it."
    },
    enabled: true,
    mounted: true,
    library_tier: "base",
    library_origin: "tcar_base_lora_library",
    base_lora: true,
    system_managed: true,
    visibility: "global",
    workspace_id: null,
    created_by: "tcar-system",
    web_access: "all_users",
    proof_status: "poc_validated",
    production_promotion_complete: false,
    knowledge_mode: "general_with_caveat",
    missing_data_policy: "answer_with_note",
    constraint_mode: "advisory_note",
    required_limitation_label: "Data note:",
    runtime_registration_audit_binding: {
      receipt_id: "ar_7c5198fc905c4a218faf18492b7b5d3a",
      receipt_hash: "2c2b610e7a7938d31dab2d21dd89a3e0d9775d03347c0bcc505acf7d8f773243",
      payload_sha256: "891571f8f851524f2d1f3984abd98b3c89227b02e16e97a7afbc94a7164ae809",
      actor_sha256: "6ff82c5db23f438e9d0339e5c4be05e426fa7bfa9cd279d1a1a39c00f5e57d11",
      source_text_sha256: null,
      agent_spec_sha256: "af6978b8a198eb811a6da3846608a41238b85e19c4472224e7dbe5a914fcf83e",
      agent_revision: "281a52744ca6414283dc7d95d78b92d7985b4003e57ea913e462a0ba419cd742",
      adapter_content_digest: "cb28b55e8f45ffd473625a639ab92144a7930477480988e8094a00b84ae9dad0",
      manifest_contract_digest: "02d2d0c0976468762602ce853c86f57257591e9529d40f226ec348db02f1189c",
      event_type: "agent.registered",
      subject_sequence: 5,
      chain_snapshot_sequence: 5,
      chain_snapshot_head_hash: "2c2b610e7a7938d31dab2d21dd89a3e0d9775d03347c0bcc505acf7d8f773243",
      adoption_head_receipt_id: "ar_7c5198fc905c4a218faf18492b7b5d3a",
      adoption_head_receipt_hash: "2c2b610e7a7938d31dab2d21dd89a3e0d9775d03347c0bcc505acf7d8f773243"
    }
  },
  {
    id: "product_strategy_lora",
    title: "Product strategy, customer segments, value proposition, and launch framing",
    capability: "Frames target users, value proposition, launch assumptions, and product constraints.",
    boundary: "Stays at product strategy level and does not make legal, medical, or finance claims.",
    consumes: ["user_request", "market_context"],
    produces: ["business_context", "target_users", "product_constraints", "launch_assumptions"],
    routing_cues: ["product", "positioning", "market", "launch", "customer segment", "value proposition"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 10,
    skill_path: "skills/tcar_dummy_loras/product_strategy_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/product_strategy_lora",
    contract_version: "tcar-agent-v1",
    policies: { activation_policy: "Use for product and go-to-market framing." },
    enabled: true,
    mounted: true
  },
  {
    id: "research_literature_lora",
    title: "Research literature triage, evidence summaries, source quality, and caveats",
    capability: "Summarizes evidence quality, source caveats, and research search terms.",
    boundary: "Does not invent citations and flags uncertainty when sources are missing.",
    consumes: ["user_request", "source_context"],
    produces: ["evidence_summary", "source_caveats", "research_terms"],
    routing_cues: ["research", "literature", "evidence", "paper", "study", "sources"],
    resources: [],
    tools: ["search_index"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 12,
    skill_path: "skills/tcar_dummy_loras/research_literature_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/research_literature_lora",
    contract_version: "tcar-agent-v1",
    policies: { tool_policy: "Only search approved indexes." },
    enabled: true,
    mounted: true
  },
  {
    id: "linear_algebra_textbook_lora",
    title: "Uploaded linear algebra textbook source agent",
    capability: "Retrieves cited definitions, examples, and constraints from the uploaded textbook source.",
    boundary: "Use only retrieved document chunks for textbook-specific claims.",
    consumes: ["user_request", "document_context"],
    produces: ["retrieved_context", "cited_passages", "document_constraints", "source_confidence"],
    routing_cues: ["linear algebra", "rank-nullity", "textbook", "linear map", "uploaded document"],
    resources: ["linear_algebra_textbook"],
    tools: ["document_search", "document_read"],
    sources: ["sources/tcar_documents/linear_algebra_textbook/index.jsonl"],
    retrieval: { type: "document_markdown", top_k: 4 },
    document: { slug: "linear_algebra_textbook", title: "Linear algebra textbook" },
    stage: 13,
    skill_path: "skills/tcar_dummy_loras/linear_algebra_textbook_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/linear_algebra_textbook_lora",
    contract_version: "tcar-agent-v1",
    policies: { citation_policy: "Cite chunk ids and page metadata when available." },
    enabled: true,
    mounted: true
  },
  {
    id: "legal_privacy_lora",
    title: "Legal-information boundaries, privacy, consent, records, and policy risk",
    capability: "Flags consent, privacy, records, and legal-risk categories for general information.",
    boundary: "Give general legal information, not legal advice.",
    consumes: ["user_request", "policy_context", "upstream_constraints"],
    produces: ["privacy_constraints", "policy_boundaries", "records_needed", "legal_risks"],
    routing_cues: ["privacy", "consent", "legal", "records", "policy", "terms"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 15,
    skill_path: "skills/tcar_dummy_loras/legal_privacy_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/legal_privacy_lora",
    contract_version: "tcar-agent-v1",
    policies: { escalation_policy: "Escalate fact-specific legal questions to counsel." },
    enabled: true,
    mounted: true
  },
  {
    id: "health_safety_lora",
    title: "Health education, symptom safety, patient communication, and care boundaries",
    capability: "Produces patient-safe language, urgent-care flags, and clinician questions.",
    boundary: "Provides health education and safety language, not diagnosis or treatment.",
    consumes: ["user_request", "upstream_constraints"],
    produces: ["health_boundaries", "urgent_flags", "patient_safe_language", "clinician_questions"],
    routing_cues: ["health", "patient", "clinic", "symptom", "medical", "safety"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 16,
    skill_path: "skills/tcar_dummy_loras/health_safety_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/health_safety_lora",
    contract_version: "tcar-agent-v1",
    policies: { escalation_policy: "Escalate urgent symptoms or patient-specific advice." },
    enabled: true,
    mounted: true
  },
  {
    id: "finance_risk_lora",
    title: "Finance, pricing, billing, budgets, refunds, and cash-flow risk",
    capability: "Identifies financial risk, pricing variables, refund rules, and budget assumptions.",
    boundary: "Provides operational finance analysis, not investment, tax, or accounting advice.",
    consumes: ["user_request", "policy_context"],
    produces: ["financial_risks", "pricing_variables", "refund_rules", "budget_assumptions"],
    routing_cues: ["finance", "billing", "refund", "budget", "cash flow", "pricing"],
    resources: [],
    tools: ["calculator"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 18,
    skill_path: "skills/tcar_dummy_loras/finance_risk_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/finance_risk_lora",
    contract_version: "tcar-agent-v1",
    policies: { tool_policy: "Calculator only for arithmetic verification." },
    enabled: true,
    mounted: true
  },
  {
    id: "refund_policy_lora",
    title: "Refund policy, returns, replacements, and customer escalation rules",
    capability: "Answers refund and replacement questions by using approved policy sources.",
    boundary: "Do not invent policy or promise refunds before order context confirms eligibility.",
    consumes: ["customer_request", "order_context", "policy_context"],
    produces: ["policy_answer", "policy_boundaries", "refund_rules", "escalation_reason", "customer_message"],
    routing_cues: ["refund", "return", "replacement", "damaged item", "policy"],
    resources: ["refund_policy_source"],
    tools: ["policy_lookup"],
    sources: ["sources/tcar_dummy_loras/refund_policy/refund_policy.md"],
    retrieval: { type: "approved_markdown_source" },
    document: null,
    stage: 20,
    skill_path: "skills/tcar_dummy_loras/refund_policy_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/refund_policy_lora",
    contract_version: "tcar-agent-v1",
    policies: { citation_policy: "Reference the approved refund policy source." },
    enabled: true,
    mounted: true
  },
  {
    id: "software_architect_lora",
    title: "Software architecture, APIs, data models, web apps, and implementation plans",
    capability: "Plans architecture, APIs, data models, test strategy, and deployment risks.",
    boundary: "Does not claim repository facts unless inspected or provided.",
    consumes: ["user_request", "repo_context"],
    produces: ["architecture", "api_plan", "data_model", "data_flows", "test_plan", "deployment_risks"],
    routing_cues: ["software", "api", "web app", "architecture", "database", "implementation"],
    resources: [],
    tools: ["repo_inspector"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 25,
    skill_path: "skills/tcar_dummy_loras/software_architect_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/software_architect_lora",
    contract_version: "tcar-agent-v1",
    policies: { tool_policy: "Repo inspector only for supplied repository context." },
    enabled: true,
    mounted: true
  },
  {
    id: "sql_analytics_lora",
    title: "SQL analytics, warehouse checks, dashboards, reconciliation, and query validation",
    capability: "Produces metric definitions, query plans, data quality tests, and reconciliation checks.",
    boundary: "Does not execute unapproved SQL or modify data.",
    consumes: ["user_request", "schema_context"],
    produces: ["query_plan", "metric_definitions", "dataset_summary", "data_quality_tests"],
    routing_cues: ["sql", "warehouse", "analytics", "dashboard", "metric", "query"],
    resources: [],
    tools: ["sql_runner"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 28,
    skill_path: "skills/tcar_dummy_loras/sql_analytics_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/sql_analytics_lora",
    contract_version: "tcar-agent-v1",
    policies: { tool_policy: "Read-only SQL runner only." },
    enabled: true,
    mounted: true
  },
  {
    id: "data_math_tool_lora",
    title: "Data analysis, arithmetic, CSV/table calculations, and quantitative verification",
    capability: "Computes metrics, formulas, calculation traces, and sanity checks.",
    boundary: "Clearly separates calculations from assumptions.",
    consumes: ["user_request", "table_context"],
    produces: ["computed_metrics", "formula", "calculation_trace", "sanity_checks"],
    routing_cues: ["calculate", "csv", "table", "math", "numbers", "verify"],
    resources: [],
    tools: ["data_table", "calculator"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 30,
    skill_path: "skills/tcar_dummy_loras/data_math_tool_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/data_math_tool_lora",
    contract_version: "tcar-agent-v1",
    policies: { tool_policy: "Use calculator and table tools only." },
    enabled: true,
    mounted: true
  },
  {
    id: "science_reasoning_lora",
    title: "Science reasoning, engineering constraints, empirical mechanisms, and technical caveats",
    capability: "Explains scientific rationale, mechanisms, engineering constraints, and caveats.",
    boundary: "Distinguishes evidence, mechanism, and speculation.",
    consumes: ["user_request", "technical_context"],
    produces: ["scientific_rationale", "technical_caveats", "mechanism_summary"],
    routing_cues: ["science", "engineering", "mechanism", "empirical", "physics", "chemistry"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 35,
    skill_path: "skills/tcar_dummy_loras/science_reasoning_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/science_reasoning_lora",
    contract_version: "tcar-agent-v1",
    policies: {},
    enabled: true,
    mounted: true
  },
  {
    id: "security_review_lora",
    title: "Security review, abuse cases, auth, data protection, and deployment hardening",
    capability: "Finds security risks, abuse cases, hardening steps, and security tests.",
    boundary: "Provides defensive review only.",
    consumes: ["user_request", "architecture_context"],
    produces: ["security_risks", "abuse_cases", "hardening_steps", "security_tests"],
    routing_cues: ["security", "auth", "abuse", "hardening", "threat", "data protection"],
    resources: [],
    tools: ["repo_inspector"],
    sources: [],
    retrieval: null,
    document: null,
    stage: 38,
    skill_path: "skills/tcar_dummy_loras/security_review_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/security_review_lora",
    contract_version: "tcar-agent-v1",
    policies: { escalation_policy: "Do not provide exploit instructions." },
    enabled: true,
    mounted: true
  },
  {
    id: "visualization_lora",
    title: "Charts, dashboards, visual summaries, and data presentation choices",
    capability: "Recommends chart types, visual summaries, and dashboard layouts.",
    boundary: "Does not fabricate data or measurements.",
    consumes: ["user_request", "data_context"],
    produces: ["chart_recommendation", "visual_summary", "dashboard_layout"],
    routing_cues: ["chart", "visualization", "dashboard", "graph", "plot"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 40,
    skill_path: "skills/tcar_dummy_loras/visualization_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/visualization_lora",
    contract_version: "tcar-agent-v1",
    policies: {},
    enabled: true,
    mounted: true
  },
  {
    id: "education_curriculum_lora",
    title: "Education, curriculum, lesson plans, worksheets, rubrics, and assessments",
    capability: "Creates learning outcomes, lesson plans, worksheets, assessments, and student activities.",
    boundary: "Adapts to audience and avoids unsupported claims.",
    consumes: ["user_request", "learning_context"],
    produces: ["learning_outcomes", "lesson_plan", "worksheet", "assessment", "student_activity"],
    routing_cues: ["lesson", "curriculum", "student", "rubric", "worksheet", "teach"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 42,
    skill_path: "skills/tcar_dummy_loras/education_curriculum_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/education_curriculum_lora",
    contract_version: "tcar-agent-v1",
    policies: {},
    enabled: true,
    mounted: true
  },
  {
    id: "project_planning_lora",
    title: "Project planning, sequencing, milestones, owners, rollout, and checklists",
    capability: "Builds timelines, checklists, owners, milestones, and rollout plans.",
    boundary: "Does not overfit plans to unknown team capacity.",
    consumes: ["user_request", "constraints"],
    produces: ["timeline", "checklist", "owners", "milestones", "next_steps"],
    routing_cues: ["plan", "roadmap", "timeline", "milestone", "rollout", "checklist"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 45,
    skill_path: "skills/tcar_dummy_loras/project_planning_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/project_planning_lora",
    contract_version: "tcar-agent-v1",
    policies: {},
    enabled: true,
    mounted: true
  },
  {
    id: "customer_support_lora",
    title: "Customer support, FAQs, escalation paths, help-center language, and service recovery",
    capability: "Drafts support FAQs, escalation paths, customer messages, and service boundaries.",
    boundary: "Does not make promises beyond approved policy and upstream constraints.",
    consumes: ["user_request", "policy_boundaries", "health_boundaries", "refund_rules"],
    produces: ["support_faq", "escalation_path", "customer_message", "support_boundaries"],
    routing_cues: ["support", "faq", "customer", "help center", "reply", "message"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 60,
    skill_path: "skills/tcar_dummy_loras/customer_support_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/customer_support_lora",
    contract_version: "tcar-agent-v1",
    policies: {},
    enabled: true,
    mounted: true
  },
  {
    id: "writing_synthesis_lora",
    title: "Writing synthesis, executive summaries, emails, memos, templates, and final prose",
    capability: "Synthesizes route outputs into concise final prose and user-facing formats.",
    boundary: "Preserves upstream safety boundaries and source caveats.",
    consumes: ["upstream_route_outputs", "user_request"],
    produces: ["final_answer", "summary", "email", "memo", "template", "executive_update"],
    routing_cues: ["draft", "write", "summarize", "email", "memo", "final answer"],
    resources: [],
    tools: [],
    sources: [],
    retrieval: null,
    document: null,
    stage: 90,
    skill_path: "skills/tcar_dummy_loras/writing_synthesis_lora/SKILL.md",
    adapter_path: "adapters/dummy_tcar_loras/writing_synthesis_lora",
    contract_version: "tcar-agent-v1",
    policies: { write_policy: "Use clear final prose and keep caveats visible." },
    enabled: true,
    mounted: true
  }
];

export const approvedSourceSnippets = {
  "sources/tcar_dummy_loras/refund_policy/refund_policy.md": {
    title: "Refund Policy Source",
    excerpt:
      "Damaged-on-arrival claims require a photo and order details within 7 days. Support may offer replacement or refund after eligibility is confirmed.",
    score: 1
  }
};
